"""Generate native constants from the vendored scheme (stdlib only)."""
import argparse
import json
from pathlib import Path
root = Path(__file__).resolve().parents[1]
scheme = json.loads((root/'schemes/serialization_scheme.json').read_text())
lines = ['// Generated by scripts/generate-native-scheme.py; do not edit.',
         '#include <cstdint>', '#include <string>', '#include <set>',
         'constexpr int64_t scheme_magic = '+str(scheme['wire']['magic'])+';',
         'constexpr int64_t scheme_protocol = '+str(scheme['wire']['protocol'])+';',
         'inline std::string scheme_operation(int op) { switch(op) {']
for name, value in scheme['operations'].items():
    lines.append('case '+str(value)+': return '+json.dumps(name[3:].lower())+';')
lines += ['default: return std::to_string(op); }}',
          'inline bool scheme_version(const std::string& name, int v) {']
for name, versions in scheme['class_versions'].items():
    lines.append('if(name=='+json.dumps(name)+') return '+' || '.join('v=='+str(v) for v in versions)+';')
lines += ['return false; }']
for kind, names in {
    'unary': 'neg exp log sqrt sq twice sin cos tan asin acos atan not floor ceil fabs sign erf inv sinh cosh tanh asinh acosh atanh',
    'binary': 'add sub mul div pow constpow lt le eq ne and or fmod copysign if_else_zero fmin fmax atan2',
}.items():
    lines += ['inline bool is_'+kind+'(const std::string& name) {',
              'static const std::set<std::string> names = {'+', '.join(map(json.dumps, names.split()))+'};',
              'return names.count(name)!=0; }']
output = root/'native/src/scheme.hpp'
text = '\n'.join(lines)+'\n'
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
if args.check:
    if output.read_text() != text:
        parser.exit(1, 'Native scheme constants are stale; regenerate them\n')
else:
    output.write_text(text)
