"""Compile vendored serialization metadata into reader source assets (stdlib only)."""
import argparse
import json
from pathlib import Path
import pprint


def native_header(scheme):
    lines = ['// Generated by scripts/generate-reader-assets.py; do not edit.',
             '#include <cstdint>', '#include <string>', '#include <set>',
             'constexpr int64_t scheme_magic = '+str(scheme['wire']['magic'])+';',
             'constexpr int64_t scheme_protocol = '+str(scheme['wire']['protocol'])+';',
             'inline std::string scheme_operation(int op) { switch(op) {']
    for name, value in scheme['operations'].items():
        lines.append('case '+str(value)+': return '+json.dumps(name[3:].lower())+';')
    lines += ['default: return std::to_string(op); }}',
              'inline bool scheme_version(const std::string& name, int v) {']
    for name, versions in scheme['class_versions'].items():
        lines.append('if(name=='+json.dumps(name)+') return '+' || '.join('v=='+str(v) for v in versions)+';')
    lines += ['return false; }']
    for kind, names in {
        'unary': 'neg exp log sqrt sq twice sin cos tan asin acos atan not floor ceil fabs sign erf inv sinh cosh tanh asinh acosh atanh',
        'binary': 'add sub mul div pow constpow lt le eq ne and or fmod copysign if_else_zero fmin fmax atan2',
    }.items():
        lines += ['inline bool is_'+kind+'(const std::string& name) {',
                  'static const std::set<std::string> names = {'+', '.join(map(json.dumps, names.split()))+'};',
                  'return names.count(name)!=0; }']
    return '\n'.join(lines)+'\n'


def generate(root):
    scheme = json.loads((root/'schemes/serialization_scheme.json').read_text())
    if scheme['format'] != 'casadi_serialization_scheme' or scheme['version'] != 1:
        raise ValueError('Unsupported serialization scheme')
    metadata = {
        'wire': {key: scheme['wire'][key] for key in ('magic', 'protocol')},
        'operations': scheme['operations'],
        'class_versions': scheme['class_versions'],
    }
    comment = 'Generated by scripts/generate-reader-assets.py; do not edit.'
    return {
        'native/src/scheme.hpp': native_header(scheme),
        'src/scheme.js': '// '+comment+'\nexport default '+json.dumps(metadata, indent=2)+';\n',
        'python/casadi_reader/_scheme.py': '# '+comment+'\nSCHEME = '+pprint.pformat(metadata, sort_dicts=True)+'\n',
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    stale = []
    for relative, text in generate(root).items():
        output = root/relative
        if args.check:
            if not output.exists() or output.read_text() != text:
                stale.append(relative)
        else:
            output.write_text(text)
    if stale:
        parser.exit(1, 'Stale reader assets: '+', '.join(stale)+'; run npm run generate\n')


if __name__ == '__main__':
    main()
