"""Language backends: scheme data plus thin, separately maintained templates."""
import json
import pprint
from pathlib import Path


class Generator:
    templates = {}

    def __init__(self, root, scheme):
        self.root = root
        self.data = {'wire': {k: scheme['wire'][k] for k in ('magic', 'protocol')},
                     'reader': scheme['reader']}

    def generate(self):
        return {output: (self.root/'scripts/templates'/template).read_text()
                for output, template in self.templates.items()}


class JavaScriptGenerator(Generator):
    templates = {'src/index.js': 'javascript/index.js.in',
                 'src/source.js': 'javascript/source.js.in'}

    def generate(self):
        return {**super().generate(), 'src/scheme.js':
                '// Generated by scripts/generate-reader-assets.py; do not edit.\n'
                'export default '+json.dumps(self.data, indent=2)+';\n'}


class PythonGenerator(Generator):
    templates = {'python/casadi_reader/reader.py': 'python/reader.py.in',
                 'python/casadi_reader/__main__.py': 'python/__main__.py.in',
                 'python/casadi_reader/__init__.py': 'python/__init__.py.in'}

    def generate(self):
        return {**super().generate(), 'python/casadi_reader/_scheme.py':
                '# Generated by scripts/generate-reader-assets.py; do not edit.\n'
                'SCHEME = '+pprint.pformat(self.data, sort_dicts=True)+'\n'}


class NativeGenerator(Generator):
    # C++ engine, C ABI, and C++ RAII interface share one structural interpreter.
    templates = {'native/src/reader.cpp': 'native/reader.cpp.in',
                 'native/src/main.cpp': 'native/main.cpp.in',
                 'native/include/casadi_reader/reader.h': 'native/reader.h.in',
                 'native/include/casadi_reader/reader.hpp': 'native/reader.hpp.in'}

    def generate(self):
        return {**super().generate(), 'native/src/scheme.hpp':
                '// Generated by scripts/generate-reader-assets.py; do not edit.\n'
                'static const char scheme_json[] = R"CASADI_SCHEME('
                +json.dumps(self.data, separators=(',', ':'))+')CASADI_SCHEME";\n'}


class MatlabGenerator(Generator):
    templates = {'matlab/casadi_reader_mex.cpp': 'matlab/casadi_reader_mex.cpp.in',
                 'matlab/+casadi_reader/Document.m': 'matlab/+casadi_reader/Document.m.in',
                 'matlab/+casadi_reader/read.m': 'matlab/+casadi_reader/read.m.in'}


class JuliaGenerator(Generator):
    templates = {'julia/src/CasadiReader.jl': 'julia/CasadiReader.jl.in',
                 'julia/Project.toml': 'julia/Project.toml.in'}


GENERATORS = (JavaScriptGenerator, PythonGenerator, NativeGenerator, MatlabGenerator, JuliaGenerator)
